version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432 && !</dev/tcp/db_test/6000; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0'
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET: ${SECRET}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: